### ISSUE TITLE
Units of parameters in parameters_initialstate.nml?

### ISSUE THREAD

**Issue by serbinsh** [wengensheng/ForestESS#1]
https://github.com/wengensheng/ForestESS/blob/master/parameters_initialstate.nml

@wengensheng Can I find the units for the parameters in one of your manuscripts?

Thanks!

**Comment by wengensheng** [comment]
I have updated the units in this file. More details can be found in the Table 2 of Weng et al. 2017 Global Change Biology (http://onlinelibrary.wiley.com/doi/10.1111/gcb.13542/abstract) and appendixes in Weng et al. 2015 Biogeosciences (http://www.biogeosciences.net/12/2655/2015/bg-12-2655-2015.html).

**Comment by serbinsh** [comment]
Thanks!!!

S
------------------------------------------------------------------------------
Shawn P. Serbin
Associate Scientist
Environmental & Climate Sciences Department
Brookhaven National Laboratory
Upton, NY 11973-5000

Phone: +1 631-344-3165
Fax: +1 631-344-2060
Email: sserbin@bnl.gov<mailto:sserbin@bnl.gov>
Bio:  http://www.bnl.gov/envsci/bio/serbin-shawn.php
TEST Group: http://www.bnl.gov/TEST/
ORCiD: http://orcid.org/0000-0003-4136-8971
Twitter: @doctorjackpine, @test_bnl
------------------------------------------------------------------------------

On Jun 7, 2017, at 9:03 AM, Ensheng Weng <notifications@github.com<mailto:notifications@github.com>> wrote:


I have updated the units in this file. More details can be found in the Table 2 of Weng et al. 2017 Global Change Biology (http://onlinelibrary.wiley.com/doi/10.1111/gcb.13542/abstract) and appendixes in Weng et al. 2015 Biogeosciences (http://www.biogeosciences.net/12/2655/2015/bg-12-2655-2015.html).
